site_name: MTR-ANTE NEST Patch
theme:
  name: material
  features:
    - navigation.sections
  logo: assets/logo.png
  favicon: images/favicon.png

extra:
  social:
    - icon: fontawesome/brands/discord 
      name: NEST Technology
      link: https://discord.gg/x8HBB3gaE6

plugins:
  - tags:
  - search:
      enabled: false

features:
  - navigation.instant
  - navigation.instant.progress

copyright: © 2025 ねすと(NEST) Modの利用にはMTR-ANTE NEST Patch 利用ルールが適用されます。

markdown_extensions:
  - material.extensions.preview:
      configurations:
        - targets:
            include:
              - changelog/index.md
              - customization.md
              - insiders/changelog/*
              - setup/extensions/*
              
  - admonition
  - pymdownx.details
  - pymdownx.superfences